version: '3.3'
services:

  main:
    container_name: main
    build:
      context: .
      dockerfile: ./main/Dockerfile
    volumes:
      - ./main:/app
    ports:
      - "3000:3000"

  userdb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    restart: always
    environment:
      # MONGO_INITDB_ROOT_USERNAME: root
      # MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: demo
    volumes:
      - ./fixtures/init-users.js:/docker-entrypoint-initdb.d/init-users.js:ro
      - /data/db

  mongo-express:
    container_name: mongo-ui
    image: mongo-express
    ports:
      - "8081:8081"
    restart: always
    environment:
      # ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      # ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_SERVER: userdb